# Generated by Django 4.1.7 on 2023-05-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_grade_group_userregistrationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationinfo',
            name='login_source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
