# Generated by Django 4.1.7 on 2023-05-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.BooleanField(choices=[(False, 'Student'), (True, 'Teacher')], default=False),
        ),
    ]
